service:
  base_url: "https://crispy-potato-694g7jjp6rjxf4677-8000.app.github.dev"
strings:
  no_rights: "Пользователь {username} не имеет прав администратора."
  admin_menu:
    title: "Меню администратора 🔑"
    export_data: "Экспорт данных"
  menu:
    modes:
      step_by_step: "Пошаговое объеснение"
      short: "Краткое объяснение"
    billing: "Тариф"
    feedback: "Обратная связь"