llm:
  config:
    default:
      _target_: telegram_llm_chatbot.api.schemas.ModelConfig
      model_name: "accounts/fireworks/models/llama-v3-70b-instruct"
      chat_history_limit: 10
      max_tokens: 2500
      temperature: 0.7
      provider: "fireworksai"

api:
    version: "0.1.0"
    title: "LLM Chatbot API"
    description: "API for interaction with llm chatbot"
    host: "0.0.0.0"
    port: 8000