dalle3:
  _target_: telegram_llm_chatbot.api.schemas.DalleConfig
  model_name: "dall-e-3"
  n: 1
  quality: "standard"
  size: "1024x1024"
strings:
  cancel: "Отмена"
  ask_description: "Пришлите формат изображения:"
  ask_size:
    title: "Выберите размер изображения:"
    options:
      - label: "квадратный"
        value: "1024x1024"
      - label: "вертикальный"
        value: "1024x1792"
      - label: "горизонтальный"
        value: "1792x1024"
  please_wait: "Изображение создаётся …"