custom:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  chat_history_limit: 10
  max_tokens: 2000
  model_name: accounts/fireworks/models/gemma2-9b-it
  provider: fireworksai
  stream: true
  temperature: 0.7
fireworksai_gemma2:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  chat_history_limit: 10
  max_tokens: 2000
  model_name: accounts/fireworks/models/gemma2-9b-it
  provider: fireworksai
  stream: true
  temperature: 0.7
fireworksai_llama:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  chat_history_limit: 10
  max_tokens: 2000
  model_name: accounts/fireworks/models/llama-v3-70b-instruct
  provider: fireworksai
  stream: true
  temperature: 0.7
openai_gpt4o-mini:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  chat_history_limit: 10
  max_tokens: 2000
  model_name: gpt-4o-mini
  provider: openai
  stream: true
  temperature: 0.7
