fireworksai_llama:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  model_name: "accounts/fireworks/models/llama-v3-70b-instruct"
  chat_history_limit: 10
  max_tokens: 2500
  temperature: 0.7
  provider: "fireworksai"
  stream: true

openai_gpt4o:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  model_name: "gpt-4o-mini"
  chat_history_limit: 10
  max_tokens: 3000
  temperature: 0.7
  provider: "openai"
  stream: false

custom:
  _target_: telegram_llm_chatbot.api.schemas.ModelConfig
  model_name: "gpt-4o-mini"
  chat_history_limit: 10
  max_tokens: 2500
  temperature: 0.7
  provider: "openai"
  stream: true
